language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - SERVER=development
    - TOX_ENV=flake8
before_install:
    - if [[ $SERVER != development ]]; then pip install kinto; fi
    - if [[ $SERVER == development ]]; then pip install https://github.com/Kinto/kinto/zipball/master; fi
    - make install-dev
    - make runkinto &
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
