language: python
sudo: true
python: 2.7
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5
      - python3.5-dev
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py35 SERVER=development
    - TOX_ENV=flake8
before_install:
    - VIRTUAL_ENV=.venv make VIRTUALENV="virtualenv --python python3.5" install-dev
    - VIRTUAL_ENV=.venv make VIRTUALENV="virtualenv --python python3.5" runkinto &
    - if [[ $SERVER == development ]]; then .venv/bin/pip install https://github.com/Kinto/kinto/tarball/master; fi
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
