language: python
python: 3.5
env:
    - TOX_ENV=py35
    - TOX_ENV=py35 SERVER=development
before_install:
    - make install-dev
    - if [[ $SERVER == development ]]; then pip install https://github.com/Kinto/kinto/tarball/master; fi
    - make runkinto &
    - curl http://localhost:8890
install:
    - pip install tox
script:
    - tox -e $TOX_ENV -- -k Functional
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=py36 SERVER=development
    - env:
        - TOX_ENV=flake8
      before_install:
        - python --version
